### ISSUE TITLE
原始定点无法使用，需要自行设计

### ISSUE THREAD

**Issue by Dr1st** [sebuaa2019/Team108#15]
### 原始定点程序无法保存航点文件

**Comment by RyanMrW** [comment]
针对这个问题我们进行了几个尝试：

首先我们尝试了用自带的waterplus_maptools工具来进行对点的存取，但这个工具存在的问题是无法根据机器人所在位置进行保存航点，能做的只是根据地图在屏幕上画出航点的大致位置。这不符合我们的需求所以我们将之弃置（源代码见第一次尝试的src中）

然后我们试图采用的方式是采用任务脚本系统中的add_waypoints函数来进行加点。在刚开始进行调试的时候我们发现这个函数仅仅是在内存中存储了相关航点的信息，而没有在计算机中存储相应的信息。

最后我们结合这两种做法提出了一种新的做法。在调用任务脚本系统获取机器人当前位置点之后我们将信息传导给map_tools工具，运用map_tools工具进行找点、存点。

这也是我们最终的解决方案（见源码的src中和launch中对应的文件）
