### ISSUE TITLE
导出检测到的物体图片

### ISSUE THREAD

**Issue by Dr1st** [sebuaa2019/Team108#4]
### 为APP提供导出图片接口

李嘉业、王润安

**Comment by RyanMrW** [comment]
### 第一次尝试：
2019.5.16进行
整个物体识别与抓取的思路如下：
需要的前提条件：已经建完了图，并且标记了桌子的起始点、终止点。并且桌子上的物体之间的间距不少于20cm（根据机器人的视角大小确定）

1. 前往起始点
2. take a pic
3. 进行识别，或者用机器学习方法或者用人来判断是否是需要的物体。是则进行4，不是则向右移动20cm并返回2
4. 进行抓取。

首次尝试中使用了wpb_home_apps提供的任务脚本来进行到指定点和拍照的功能，但是在实际调试中出现了几个问题：

1. 封装之后的脚本能通过编译但是无法执行（缺少节点）
2. ACT_CAP_IMAGE 模块在启智机器人中并没有实现
3. 任务脚本系统存在一定问题，任务的执行结果可能会出现问题

根据这些问题下一步的一些工作

1. 如何实现不用任务脚本系统来执行各个模块
2. 如何实现照相的功能（其他功能都已经有相应的例程而照像功能咱是没有实现）
3. 有没有更好的实现方法（因为要求每个物体之间的间隔实在是有些蠢）

[这里是第一次尝试的代码](https://github.com/sebuaa2019/Team108/tree/master/%E7%89%A9%E4%BD%93%E8%AF%86%E5%88%AB%E4%B8%8E%E6%8A%93%E5%8F%96%E6%A8%A1%E5%9D%97/%E5%BC%83%E7%BD%AE%E7%9A%84%E4%BB%A3%E7%A0%81/team_108)

**Comment by RyanMrW** [comment]
# 第二次尝试（最终）

经过一些代码尝试（可见弃置的代码）和调试的尝试，我们最终放弃了这个想法。原因有如下的几个：

首先是对于抓取物体的特性还不够好，在调试的过程中出现了很多次检测不到指定物体和检测到了物体到时并没有能够成功抓取的案例。我们在这上面花费了大量的时间。

其次是我们对抓取指定物体进行了一定的尝试，但是在调试中抓取到指定物体仍然存在问题。下面简述一下我们尝试的思路（代码可见弃置的代码）：
1. 进行识别，并进行照相
2. 对识别到的物体按照方位的顺序进行排序
3. 模拟机器学习的步骤，指定一个物体抓取

遗憾的是在我们的大量多次调试过程中机器人并没有抓取到我们指定的物体，并出现了很多次没有找到物体、没有抓到物体的情况。

最终我们决定把时间投入到如何让机器人更精确的抓起物体上。
